In [4]:
import tensorflow as tf
from tensorflow import keras as ks, float32
import numpy as np
from tensorflow.python.ops import math_ops, array_ops
batch_size=3
nbre_copies=9
height=11
width=11
range = math_ops.range(nbre_copies) * height * width
offsets = array_ops.reshape(range, [nbre_copies, 1])
batch_offsets2 = tf.tile(offsets, [batch_size, 1])
batch_offsets = tf.reshape(batch_offsets2, [-1, nbre_copies, 1])
a = tf.range(11)
batch_offsets = batch_offsets * a
batch_offsets2 = batch_offsets2 * a

print(batch_offsets2.shape)
flattened_grid = tf.random.uniform(shape=(batch_size, 20736, 65))
flattened_grid2 = tf.reshape(flattened_grid, (-1, 65))
print(flattened_grid2.shape)
gather2 = tf.gather(flattened_grid2, batch_offsets2)
print(gather2.shape)
print(batch_offsets.shape)
print(flattened_grid.shape)
print("desired:", (3, 9, a.shape[0], 65))

for idx, i in enumerate(batch_offsets):
    z = tf.gather(flattened_grid[idx], batch_offsets[idx])
    print(z.shape)
    print("-")

gather = tf.gather(flattened_grid, batch_offsets,batch_dims=1)

print(gather.shape)




(27, 11)
(62208, 65)
(27, 11, 65)
(3, 9, 11)
(3, 20736, 65)
desired: (3, 9, 11, 65)
(9, 11, 65)
-
(9, 11, 65)
-
(9, 11, 65)
-
(3, 9, 11, 65)


In [9]:
flow_former_test_1 = tf.random.uniform((8, 1, 1, 2))
combined_former_test_1 = tf.random.uniform((45, 1, 1, 4))
print(flow_former_test_1)
print(tf.reshape(flow_former_test_1, (-1, 4, 1, 1, 2)))
flow_test_1 = tf.random.uniform((5, 9, 48, 48, 2))
combined_test_1 = tf.random.uniform((5, 9, 48, 48, 65))


tf.Tensor(
[[[[0.833434   0.79107535]]]


 [[[0.29519367 0.4234035 ]]]


 [[[0.1157856  0.25174618]]]


 [[[0.90367484 0.7267879 ]]]


 [[[0.8352047  0.17344809]]]


 [[[0.41357303 0.02898276]]]


 [[[0.8451811  0.92669356]]]


 [[[0.94708717 0.23317397]]]], shape=(8, 1, 1, 2), dtype=float32)
tf.Tensor(
[[[[[0.833434   0.79107535]]]


  [[[0.29519367 0.4234035 ]]]


  [[[0.1157856  0.25174618]]]


  [[[0.90367484 0.7267879 ]]]]



 [[[[0.8352047  0.17344809]]]


  [[[0.41357303 0.02898276]]]


  [[[0.8451811  0.92669356]]]


  [[[0.94708717 0.23317397]]]]], shape=(2, 4, 1, 1, 2), dtype=float32)


In [2]:
a = 23 / 2. ** float(4)
b = 23 / (2. ** float(4))
b = b
print(a, b)

1.4375 1.4375


In [5]:
a = 2
b = 3
c = 5
if a == b or c:
    print("ok")

ok


In [5]:
from tensorflow import keras as ks, float32
import tensorflow as tf

a = ks.Input(shape=(384, 384, 3,), dtype=float32)
b = tf.keras.layers.concatenate([a, a, a, a],
                                axis=-1)
print(b)

KerasTensor(type_spec=TensorSpec(shape=(None, 384, 384, 12), dtype=tf.float32, name=None), name='concatenate_3/concat:0', description="created by layer 'concatenate_3'")


In [2]:
print(vae.summary(expand_nested=True))
print(vae.layers)

Model: "autoencoder"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 encoder (Encoder)           multiple                  54400     
                                                                 
 decoder (Decoder)           multiple                  53072     
                                                                 
Total params: 107,472
Trainable params: 107,472
Non-trainable params: 0
_________________________________________________________________
None
[<__main__.Encoder object at 0x7fe678520640>, <__main__.Decoder object at 0x7fe65e024b50>]


In [3]:
x = keras.Input(784)
model = Model(inputs=x, outputs=vae(x))
print(model.summary())

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 784)]             0         
                                                                 
 autoencoder (VariationalAut  (None, 784)              107472    
 oEncoder)                                                       
                                                                 
Total params: 107,472
Trainable params: 107,472
Non-trainable params: 0
_________________________________________________________________
None


In [6]:
from keras.utils import vis_utils

# vis_utils.plot_model(model, to_file='model.png', show_shapes=True,expand_nested=True, dpi=300)

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_1 (Dense)             (None, 2)                 10        
                                                                 
Total params: 10
Trainable params: 10
Non-trainable params: 0
_________________________________________________________________
